[package]
name = "vision_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
image = "0.25"
ndarray = "0.16.1"
fast_image_resize = "2"
ort = { version = "2.0.0-rc.10", features = ["ndarray"] }
